using Oracle.ManagedDataAccess.Client;

namespace EasyCore.Quartz;

/// <summary>
/// Ensures Quartz tables exist in Oracle.
/// </summary>
public sealed class OracleSchemaBootstrapper : IQuartzSchemaBootstrapper
{
    public async Task EnsureCreatedAsync(
        string connectionString,
        string tablePrefix,
        CancellationToken cancellationToken = default)
    {
        var p = string.IsNullOrWhiteSpace(tablePrefix) ? "QRTZ_" : tablePrefix;

        await using var connection = new OracleConnection(connectionString);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);

        async Task EnsureTableAsync(string tableName, string createSql)
        {
            await using (var check = connection.CreateCommand())
            {
                check.CommandText = "SELECT COUNT(*) FROM USER_TABLES WHERE TABLE_NAME = :name";
                check.Parameters.Add(new OracleParameter("name", tableName.ToUpperInvariant()));
                var count = Convert.ToInt32(await check.ExecuteScalarAsync(cancellationToken).ConfigureAwait(false));
                if (count > 0)
                {
                    return;
                }
            }

            await using var create = connection.CreateCommand();
            create.CommandText = createSql;
            await create.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
        }

        await EnsureTableAsync($"{p}JOB_DETAILS", $@"
CREATE TABLE {p}JOB_DETAILS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  JOB_NAME VARCHAR2(200) NOT NULL,
  JOB_GROUP VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(250) NULL,
  JOB_CLASS_NAME VARCHAR2(250) NOT NULL,
  IS_DURABLE VARCHAR2(1) NOT NULL,
  IS_NONCONCURRENT VARCHAR2(1) NOT NULL,
  IS_UPDATE_DATA VARCHAR2(1) NOT NULL,
  REQUESTS_RECOVERY VARCHAR2(1) NOT NULL,
  JOB_DATA BLOB NULL,
  CONSTRAINT PK_{Sanitize(p)}JOB_DETAILS PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}TRIGGERS", $@"
CREATE TABLE {p}TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  JOB_NAME VARCHAR2(200) NOT NULL,
  JOB_GROUP VARCHAR2(200) NOT NULL,
  DESCRIPTION VARCHAR2(250) NULL,
  NEXT_FIRE_TIME NUMBER(19) NULL,
  PREV_FIRE_TIME NUMBER(19) NULL,
  PRIORITY NUMBER(13) NULL,
  TRIGGER_STATE VARCHAR2(16) NOT NULL,
  TRIGGER_TYPE VARCHAR2(8) NOT NULL,
  START_TIME NUMBER(19) NOT NULL,
  END_TIME NUMBER(19) NULL,
  CALENDAR_NAME VARCHAR2(200) NULL,
  MISFIRE_INSTR NUMBER(2) NULL,
  JOB_DATA BLOB NULL,
  CONSTRAINT PK_{Sanitize(p)}TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  CONSTRAINT FK_{Sanitize(p)}TRIGGERS_JOBS FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
    REFERENCES {p}JOB_DETAILS(SCHED_NAME, JOB_NAME, JOB_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}SIMPLE_TRIGGERS", $@"
CREATE TABLE {p}SIMPLE_TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  REPEAT_COUNT NUMBER(7) NOT NULL,
  REPEAT_INTERVAL NUMBER(12) NOT NULL,
  TIMES_TRIGGERED NUMBER(10) NOT NULL,
  CONSTRAINT PK_{Sanitize(p)}SIMPLE_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  CONSTRAINT FK_{Sanitize(p)}SIMPLE_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}CRON_TRIGGERS", $@"
CREATE TABLE {p}CRON_TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  CRON_EXPRESSION VARCHAR2(120) NOT NULL,
  TIME_ZONE_ID VARCHAR2(80),
  CONSTRAINT PK_{Sanitize(p)}CRON_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  CONSTRAINT FK_{Sanitize(p)}CRON_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}SIMPROP_TRIGGERS", $@"
CREATE TABLE {p}SIMPROP_TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  STR_PROP_1 VARCHAR2(512) NULL,
  STR_PROP_2 VARCHAR2(512) NULL,
  STR_PROP_3 VARCHAR2(512) NULL,
  INT_PROP_1 NUMBER(10) NULL,
  INT_PROP_2 NUMBER(10) NULL,
  LONG_PROP_1 NUMBER(19) NULL,
  LONG_PROP_2 NUMBER(19) NULL,
  DEC_PROP_1 NUMBER(13,4) NULL,
  DEC_PROP_2 NUMBER(13,4) NULL,
  BOOL_PROP_1 VARCHAR2(1) NULL,
  BOOL_PROP_2 VARCHAR2(1) NULL,
  TIME_ZONE_ID VARCHAR2(80) NULL,
  CONSTRAINT PK_{Sanitize(p)}SIMPROP_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  CONSTRAINT FK_{Sanitize(p)}SIMPROP_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}BLOB_TRIGGERS", $@"
CREATE TABLE {p}BLOB_TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  BLOB_DATA BLOB NULL,
  CONSTRAINT PK_{Sanitize(p)}BLOB_TRIGGERS PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  CONSTRAINT FK_{Sanitize(p)}BLOB_TRIGGERS FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS(SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}CALENDARS", $@"
CREATE TABLE {p}CALENDARS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  CALENDAR_NAME VARCHAR2(200) NOT NULL,
  CALENDAR BLOB NOT NULL,
  CONSTRAINT PK_{Sanitize(p)}CALENDARS PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}PAUSED_TRIGGER_GRPS", $@"
CREATE TABLE {p}PAUSED_TRIGGER_GRPS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  CONSTRAINT PK_{Sanitize(p)}PAUSED_TRIGGER_GRPS PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}FIRED_TRIGGERS", $@"
CREATE TABLE {p}FIRED_TRIGGERS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  ENTRY_ID VARCHAR2(140) NOT NULL,
  TRIGGER_NAME VARCHAR2(200) NOT NULL,
  TRIGGER_GROUP VARCHAR2(200) NOT NULL,
  INSTANCE_NAME VARCHAR2(200) NOT NULL,
  FIRED_TIME NUMBER(19) NOT NULL,
  SCHED_TIME NUMBER(19) NOT NULL,
  PRIORITY NUMBER(13) NOT NULL,
  STATE VARCHAR2(16) NOT NULL,
  JOB_NAME VARCHAR2(200) NULL,
  JOB_GROUP VARCHAR2(200) NULL,
  IS_NONCONCURRENT VARCHAR2(1) NULL,
  REQUESTS_RECOVERY VARCHAR2(1) NULL,
  CONSTRAINT PK_{Sanitize(p)}FIRED_TRIGGERS PRIMARY KEY (SCHED_NAME, ENTRY_ID)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}SCHEDULER_STATE", $@"
CREATE TABLE {p}SCHEDULER_STATE (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  INSTANCE_NAME VARCHAR2(200) NOT NULL,
  LAST_CHECKIN_TIME NUMBER(19) NOT NULL,
  CHECKIN_INTERVAL NUMBER(19) NOT NULL,
  CONSTRAINT PK_{Sanitize(p)}SCHEDULER_STATE PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
)").ConfigureAwait(false);

        await EnsureTableAsync($"{p}LOCKS", $@"
CREATE TABLE {p}LOCKS (
  SCHED_NAME VARCHAR2(120) NOT NULL,
  LOCK_NAME VARCHAR2(40) NOT NULL,
  CONSTRAINT PK_{Sanitize(p)}LOCKS PRIMARY KEY (SCHED_NAME, LOCK_NAME)
)").ConfigureAwait(false);
    }

    private static string Sanitize(string prefix) =>
        new string(prefix.Where(char.IsLetterOrDigit).ToArray());
}
