using Microsoft.Data.SqlClient;

namespace EasyCore.Quartz;

/// <summary>
/// Ensures Quartz tables exist in SQL Server.
/// </summary>
public sealed class SqlServerSchemaBootstrapper : IQuartzSchemaBootstrapper
{
    public async Task EnsureCreatedAsync(
        string connectionString,
        string tablePrefix,
        CancellationToken cancellationToken = default)
    {
        var dbName = ConnectionStringHelper.GetDatabaseName(connectionString)
                     ?? throw new ArgumentException("Unable to determine the database name from the connection string.");

        var p = string.IsNullOrWhiteSpace(tablePrefix) ? "QRTZ_" : tablePrefix;

        var sql = $@"
USE [{dbName}];

IF OBJECT_ID(N'[dbo].[{p}CALENDARS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}CALENDARS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [CALENDAR_NAME] NVARCHAR(200) NOT NULL,
  [CALENDAR] VARBINARY(MAX) NOT NULL,
  CONSTRAINT [PK_{p}CALENDARS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [CALENDAR_NAME])
);

IF OBJECT_ID(N'[dbo].[{p}JOB_DETAILS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}JOB_DETAILS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [JOB_NAME] NVARCHAR(150) NOT NULL,
  [JOB_GROUP] NVARCHAR(150) NOT NULL,
  [DESCRIPTION] NVARCHAR(250) NULL,
  [JOB_CLASS_NAME] NVARCHAR(250) NOT NULL,
  [IS_DURABLE] BIT NOT NULL,
  [IS_NONCONCURRENT] BIT NOT NULL,
  [IS_UPDATE_DATA] BIT NOT NULL,
  [REQUESTS_RECOVERY] BIT NOT NULL,
  [JOB_DATA] VARBINARY(MAX) NULL,
  CONSTRAINT [PK_{p}JOB_DETAILS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [JOB_NAME], [JOB_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [JOB_NAME] NVARCHAR(150) NOT NULL,
  [JOB_GROUP] NVARCHAR(150) NOT NULL,
  [DESCRIPTION] NVARCHAR(250) NULL,
  [NEXT_FIRE_TIME] BIGINT NULL,
  [PREV_FIRE_TIME] BIGINT NULL,
  [PRIORITY] INT NULL,
  [TRIGGER_STATE] NVARCHAR(16) NOT NULL,
  [TRIGGER_TYPE] NVARCHAR(8) NOT NULL,
  [START_TIME] BIGINT NOT NULL,
  [END_TIME] BIGINT NULL,
  [CALENDAR_NAME] NVARCHAR(200) NULL,
  [MISFIRE_INSTR] INT NULL,
  [JOB_DATA] VARBINARY(MAX) NULL,
  CONSTRAINT [PK_{p}TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}CRON_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}CRON_TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [CRON_EXPRESSION] NVARCHAR(120) NOT NULL,
  [TIME_ZONE_ID] NVARCHAR(80) NULL,
  CONSTRAINT [PK_{p}CRON_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}SIMPLE_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}SIMPLE_TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [REPEAT_COUNT] INT NOT NULL,
  [REPEAT_INTERVAL] BIGINT NOT NULL,
  [TIMES_TRIGGERED] INT NOT NULL,
  CONSTRAINT [PK_{p}SIMPLE_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}SIMPROP_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}SIMPROP_TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [STR_PROP_1] NVARCHAR(512) NULL,
  [STR_PROP_2] NVARCHAR(512) NULL,
  [STR_PROP_3] NVARCHAR(512) NULL,
  [INT_PROP_1] INT NULL,
  [INT_PROP_2] INT NULL,
  [LONG_PROP_1] BIGINT NULL,
  [LONG_PROP_2] BIGINT NULL,
  [DEC_PROP_1] NUMERIC(13,4) NULL,
  [DEC_PROP_2] NUMERIC(13,4) NULL,
  [BOOL_PROP_1] BIT NULL,
  [BOOL_PROP_2] BIT NULL,
  [TIME_ZONE_ID] NVARCHAR(80) NULL,
  CONSTRAINT [PK_{p}SIMPROP_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}BLOB_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}BLOB_TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [BLOB_DATA] VARBINARY(MAX) NULL,
  CONSTRAINT [PK_{p}BLOB_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}FIRED_TRIGGERS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}FIRED_TRIGGERS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [ENTRY_ID] NVARCHAR(140) NOT NULL,
  [TRIGGER_NAME] NVARCHAR(150) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  [INSTANCE_NAME] NVARCHAR(200) NOT NULL,
  [FIRED_TIME] BIGINT NOT NULL,
  [SCHED_TIME] BIGINT NOT NULL,
  [PRIORITY] INT NOT NULL,
  [STATE] NVARCHAR(16) NOT NULL,
  [JOB_NAME] NVARCHAR(150) NULL,
  [JOB_GROUP] NVARCHAR(150) NULL,
  [IS_NONCONCURRENT] BIT NULL,
  [REQUESTS_RECOVERY] BIT NULL,
  CONSTRAINT [PK_{p}FIRED_TRIGGERS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [ENTRY_ID])
);

IF OBJECT_ID(N'[dbo].[{p}PAUSED_TRIGGER_GRPS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}PAUSED_TRIGGER_GRPS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [TRIGGER_GROUP] NVARCHAR(150) NOT NULL,
  CONSTRAINT [PK_{p}PAUSED_TRIGGER_GRPS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [TRIGGER_GROUP])
);

IF OBJECT_ID(N'[dbo].[{p}SCHEDULER_STATE]', N'U') IS NULL
CREATE TABLE [dbo].[{p}SCHEDULER_STATE] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [INSTANCE_NAME] NVARCHAR(200) NOT NULL,
  [LAST_CHECKIN_TIME] BIGINT NOT NULL,
  [CHECKIN_INTERVAL] BIGINT NOT NULL,
  CONSTRAINT [PK_{p}SCHEDULER_STATE] PRIMARY KEY CLUSTERED ([SCHED_NAME], [INSTANCE_NAME])
);

IF OBJECT_ID(N'[dbo].[{p}LOCKS]', N'U') IS NULL
CREATE TABLE [dbo].[{p}LOCKS] (
  [SCHED_NAME] NVARCHAR(120) NOT NULL,
  [LOCK_NAME] NVARCHAR(40) NOT NULL,
  CONSTRAINT [PK_{p}LOCKS] PRIMARY KEY CLUSTERED ([SCHED_NAME], [LOCK_NAME])
);

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = N'FK_{p}TRIGGERS_JOB_DETAILS')
ALTER TABLE [dbo].[{p}TRIGGERS]
ADD CONSTRAINT [FK_{p}TRIGGERS_JOB_DETAILS] FOREIGN KEY ([SCHED_NAME], [JOB_NAME], [JOB_GROUP])
REFERENCES [dbo].[{p}JOB_DETAILS] ([SCHED_NAME], [JOB_NAME], [JOB_GROUP]);

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = N'FK_{p}CRON_TRIGGERS')
ALTER TABLE [dbo].[{p}CRON_TRIGGERS]
ADD CONSTRAINT [FK_{p}CRON_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [dbo].[{p}TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE;

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = N'FK_{p}SIMPLE_TRIGGERS')
ALTER TABLE [dbo].[{p}SIMPLE_TRIGGERS]
ADD CONSTRAINT [FK_{p}SIMPLE_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [dbo].[{p}TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE;

IF NOT EXISTS (SELECT * FROM sys.foreign_keys WHERE name = N'FK_{p}SIMPROP_TRIGGERS')
ALTER TABLE [dbo].[{p}SIMPROP_TRIGGERS]
ADD CONSTRAINT [FK_{p}SIMPROP_TRIGGERS] FOREIGN KEY ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP])
REFERENCES [dbo].[{p}TRIGGERS] ([SCHED_NAME], [TRIGGER_NAME], [TRIGGER_GROUP]) ON DELETE CASCADE;
";

        await using var connection = new SqlConnection(connectionString);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);
        await using var command = new SqlCommand(sql, connection);
        await command.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }
}
