using Npgsql;

namespace EasyCore.Quartz;

/// <summary>
/// Ensures Quartz tables exist in PostgreSQL.
/// </summary>
public sealed class PostgreSqlSchemaBootstrapper : IQuartzSchemaBootstrapper
{
    public async Task EnsureCreatedAsync(
        string connectionString,
        string tablePrefix,
        CancellationToken cancellationToken = default)
    {
        var p = string.IsNullOrWhiteSpace(tablePrefix) ? "QRTZ_" : tablePrefix;

        await using var connection = new NpgsqlConnection(connectionString);
        await connection.OpenAsync(cancellationToken).ConfigureAwait(false);

        // Unquoted identifiers fold to lowercase in PostgreSQL, matching Quartz queries with prefix QRTZ_.
        var sql = $@"
CREATE TABLE IF NOT EXISTS {p}JOB_DETAILS (
  SCHED_NAME TEXT NOT NULL,
  JOB_NAME TEXT NOT NULL,
  JOB_GROUP TEXT NOT NULL,
  DESCRIPTION TEXT NULL,
  JOB_CLASS_NAME TEXT NOT NULL,
  IS_DURABLE BOOL NOT NULL,
  IS_NONCONCURRENT BOOL NOT NULL,
  IS_UPDATE_DATA BOOL NOT NULL,
  REQUESTS_RECOVERY BOOL NOT NULL,
  JOB_DATA BYTEA NULL,
  PRIMARY KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS {p}TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  JOB_NAME TEXT NOT NULL,
  JOB_GROUP TEXT NOT NULL,
  DESCRIPTION TEXT NULL,
  NEXT_FIRE_TIME BIGINT NULL,
  PREV_FIRE_TIME BIGINT NULL,
  PRIORITY INTEGER NULL,
  TRIGGER_STATE TEXT NOT NULL,
  TRIGGER_TYPE TEXT NOT NULL,
  START_TIME BIGINT NOT NULL,
  END_TIME BIGINT NULL,
  CALENDAR_NAME TEXT NULL,
  MISFIRE_INSTR SMALLINT NULL,
  JOB_DATA BYTEA NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, JOB_NAME, JOB_GROUP)
    REFERENCES {p}JOB_DETAILS (SCHED_NAME, JOB_NAME, JOB_GROUP)
);

CREATE TABLE IF NOT EXISTS {p}SIMPLE_TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  REPEAT_COUNT BIGINT NOT NULL,
  REPEAT_INTERVAL BIGINT NOT NULL,
  TIMES_TRIGGERED BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS {p}CRON_TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  CRON_EXPRESSION TEXT NOT NULL,
  TIME_ZONE_ID TEXT,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS {p}SIMPROP_TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  STR_PROP_1 TEXT NULL,
  STR_PROP_2 TEXT NULL,
  STR_PROP_3 TEXT NULL,
  INT_PROP_1 INTEGER NULL,
  INT_PROP_2 INTEGER NULL,
  LONG_PROP_1 BIGINT NULL,
  LONG_PROP_2 BIGINT NULL,
  DEC_PROP_1 NUMERIC NULL,
  DEC_PROP_2 NUMERIC NULL,
  BOOL_PROP_1 BOOL NULL,
  BOOL_PROP_2 BOOL NULL,
  TIME_ZONE_ID TEXT NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS {p}BLOB_TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  BLOB_DATA BYTEA NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP),
  FOREIGN KEY (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP)
    REFERENCES {p}TRIGGERS (SCHED_NAME, TRIGGER_NAME, TRIGGER_GROUP) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS {p}CALENDARS (
  SCHED_NAME TEXT NOT NULL,
  CALENDAR_NAME TEXT NOT NULL,
  CALENDAR BYTEA NOT NULL,
  PRIMARY KEY (SCHED_NAME, CALENDAR_NAME)
);

CREATE TABLE IF NOT EXISTS {p}PAUSED_TRIGGER_GRPS (
  SCHED_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  PRIMARY KEY (SCHED_NAME, TRIGGER_GROUP)
);

CREATE TABLE IF NOT EXISTS {p}FIRED_TRIGGERS (
  SCHED_NAME TEXT NOT NULL,
  ENTRY_ID TEXT NOT NULL,
  TRIGGER_NAME TEXT NOT NULL,
  TRIGGER_GROUP TEXT NOT NULL,
  INSTANCE_NAME TEXT NOT NULL,
  FIRED_TIME BIGINT NOT NULL,
  SCHED_TIME BIGINT NOT NULL,
  PRIORITY INTEGER NOT NULL,
  STATE TEXT NOT NULL,
  JOB_NAME TEXT NULL,
  JOB_GROUP TEXT NULL,
  IS_NONCONCURRENT BOOL NULL,
  REQUESTS_RECOVERY BOOL NULL,
  PRIMARY KEY (SCHED_NAME, ENTRY_ID)
);

CREATE TABLE IF NOT EXISTS {p}SCHEDULER_STATE (
  SCHED_NAME TEXT NOT NULL,
  INSTANCE_NAME TEXT NOT NULL,
  LAST_CHECKIN_TIME BIGINT NOT NULL,
  CHECKIN_INTERVAL BIGINT NOT NULL,
  PRIMARY KEY (SCHED_NAME, INSTANCE_NAME)
);

CREATE TABLE IF NOT EXISTS {p}LOCKS (
  SCHED_NAME TEXT NOT NULL,
  LOCK_NAME TEXT NOT NULL,
  PRIMARY KEY (SCHED_NAME, LOCK_NAME)
);
";

        await using var cmd = new NpgsqlCommand(sql, connection);
        await cmd.ExecuteNonQueryAsync(cancellationToken).ConfigureAwait(false);
    }
}
